#!/bin/bash
#
#

. /opt/monitor/monitorDB

clear

readarray -t newtcols < /etc/newt/palette
myBackground=blue

newtcols_error=(
        window=,lightgray
        border=black,lightgray
        textbox=black,lightgray
        button=white,red
		
		root=,$myBackground
        checkbox=black,lightgray
        entry=,$myBackground
        label=$myBackground,
        actlistbox=,$myBackground
        helpline=,$myBackground
        roottext=green,$myBackground
        emptyscale=$myBackground
        disabledentry=$myBackground,
)

iTitle="Monitor Config Interface"
m0001="Utilize essa ferramenta para alterar as configurações da base de dados do Monitor"
m0002="Deseja prosseguir?"
m0003="Veja abaixo a configuração atual, para alterar, selecione o número a frente de cada parâmetro"
m0004="\nValor atual:"
m0005="Defina o novo endereço IP ou URL para conexão com a Pool"
m0006="Defina o novo número da porta de conexão com a Pool"
m0007="Defina o novo protocolo de conexão com a Pool"
m0008="Defina o novo algoritmo de conexão com a Pool"
m0009="Defina o endereço da sua Wallet"
m0010="Defina um nome para o parâmetro WorkerName"
m0011="Informe o seu endereço de E-mail"
m0012="Defina um proxy para conexão com a Internet"
m0013="\n        Editar os parâmetros de conexão ao Proxy"
m0014="Voltar"
m0015="Selecionar"
m0016="Cancelar"
m0017="Sair"
m0018="Salvar"
m0019="\n             Editar os parâmetros de operação"
m0020="Ativar alocação randômica de Threads"
m0021="Número de Threads simultâneas"
m0022="Número mínimo de Threads"
m0023="Número máximo de Threads"
m0024="Ativar baixo consumo de CPU"
m0025="Início do consumo baixo de CPU"
m0026="Término do consumo baixo de CPU"
m0027=""

save_DB(){
        sed -e "s%$1=$2%$1=$3%g" /opt/monitor/monitorDB \
        > /opt/monitor/monitorDB.tmp

        mv /opt/monitor/monitorDB.tmp /opt/monitor/monitorDB

        . /opt/monitor/monitorDB
}

edit_algorithm()
{
        new_algorithm=$(NEWT_COLORS="${newtcols[@]} ${newtcols_error[@]}" whiptail --inputbox "$m0004 $algorithm" 9 78 $algorithm \
                --title "$m0008" --cancel-button "$m0016" --ok-button "$m0018" 3>&1 1>&2 2>&3)

        exitstatus=$?
        if [ $exitstatus = 0 ]; then
                save_DB "algorithm" "$algorithm" "$new_algorithm"
                go_proxy
        else
            go_proxy
        fi
}

edit_protocol(){
        new_protocol=$(NEWT_COLORS="${newtcols[@]} ${newtcols_error[@]}" whiptail --inputbox "$m0004 $protocol" 9 78 $protocol \
                --title "$m0007" --cancel-button "$m0016" --ok-button "$m0018" 3>&1 1>&2 2>&3)

        exitstatus=$?
        if [ $exitstatus = 0 ]; then
                save_DB "protocol" "$protocol" "$new_protocol"
                go_proxy
        else
            go_proxy
        fi
}

edit_ipAddress(){
        new_ip=$(NEWT_COLORS="${newtcols[@]} ${newtcols_error[@]}" whiptail --inputbox "$m0004 $ip" 9 78 $ip \
                --title "$m0005" --cancel-button "$m0016" --ok-button "$m0018" 3>&1 1>&2 2>&3)

        exitstatus=$?
        if [ $exitstatus = 0 ]; then
                save_DB "ip" "$ip" "$new_ip"
                go_proxy
        else
            go_proxy
        fi
}

edit_port () {
        new_port=$(NEWT_COLORS="${newtcols[@]} ${newtcols_error[@]}" whiptail --inputbox "$m0004 $port" 9 78 $port \
                --title "$m0006" --cancel-button "$m0016" --ok-button "$m0018" 3>&1 1>&2 2>&3)

        exitstatus=$?
        if [ $exitstatus = 0 ]; then
                save_DB "port" "$port" "$new_port"
                go_proxy
        else
            go_proxy
        fi
}

edit_WalletAddress() {
        new_WalletAddress=$(NEWT_COLORS="${newtcols[@]} ${newtcols_error[@]}" whiptail --inputbox "$m0004 $WalletAddress" 9 78 $WalletAddress \
                --title "$m0009" --cancel-button "$m0016" --ok-button "$m0018" 3>&1 1>&2 2>&3)

        exitstatus=$?
        if [ $exitstatus = 0 ]; then
                save_DB "WalletAddress" "$WalletAddress" "$new_WalletAddress"
                go_proxy
        else
            go_proxy
        fi
}

edit_WorkerName() {
        new_WorkerName=$(NEWT_COLORS="${newtcols[@]} ${newtcols_error[@]}" whiptail --inputbox "$m0004 $WorkerName" 9 78 $WorkerName \
                --title "$m0010" --cancel-button "$m0016" --ok-button "$m0018" 3>&1 1>&2 2>&3)

        exitstatus=$?
        if [ $exitstatus = 0 ]; then
                save_DB "WorkerName" "$WorkerName" "$new_WorkerName"
                go_proxy
        else
            go_proxy
        fi
}

edit_Email() {
        new_Email=$(NEWT_COLORS="${newtcols[@]} ${newtcols_error[@]}" whiptail --inputbox "$m0004 $Email" 9 78 $Email \
                --title "$m0011" --cancel-button "$m0016" --ok-button "$m0018" 3>&1 1>&2 2>&3)

        exitstatus=$?
        if [ $exitstatus = 0 ]; then
                save_DB "Email" "$Email" "$new_Email"
                go_proxy
        else
            go_proxy
        fi
}

edit_proxy() {
        new_proxy=$(NEWT_COLORS="${newtcols[@]} ${newtcols_error[@]}" whiptail --inputbox "$m0004 $proxy" 9 78 $proxy \
                --title "$m0012" --cancel-button "$m0016" --ok-button "$m0018" 3>&1 1>&2 2>&3)

        exitstatus=$?
        if [ $exitstatus = 0 ]; then
                save_DB "proxy" "$proxy" "$new_proxy"
                go_proxy
        else
            go_proxy
        fi
}

go_proxy() {
        menu_proxy=$(NEWT_COLORS="${newtcols[@]} ${newtcols_error[@]}" whiptail \
                --title "$iTitle" --cancel-button "$m0014" --ok-button "$m0015" --menu "$m0013" 17 60 8 \
                "Pool-Algoritmo" "     $algorithm" \
                "Pool-Protocolo" "     $protocol" \
                "Pool-Endereço-IP" "     $ip" \
                "Pool-Porta" "     $port" \
                "Pool-Wallet-Address" "     "$(echo $WalletAddress | awk '{print substr ($0, 0, 15)}' )"..." \
                "Pool-Worker-Name" "     $WorkerName" \
                "Pool-Email" "     $Email" \
                "Internet-Proxy" "     $proxy" \
                3>&1 1>&2 2>&3)

        exitstatus=$?
        if [ $exitstatus = 0 ]; then
                case $menu_proxy in
                        Pool-Algoritmo) edit_algorithm;;
                        Pool-Protocolo) edit_protocol;;
                        Pool-Endereço-IP) edit_ipAddress;;
                        Pool-Porta) edit_port;;
                        Pool-Wallet-Address) edit_WalletAddress;;
                        Pool-Worker-Name) edit_WorkerName;;
                        Pool-Email) edit_Email;;
                        Internet-Proxy) edit_proxy;;
                esac
        else
                go_main
        fi
}

##################################################################################################################

edit_threadRandom() {

		status_1=""
		status_2=""
		
		if [ $threadRandom = "ON" ] 
		then
			status_1="ON"
			status_2="OFF"
		else
			status_1="OFF"
			status_2="ON"
		fi

        new_threadRandom=$(NEWT_COLORS="${newtcols[@]} ${newtcols_error[@]}" whiptail --radiolist \
			" " 8 60 2 \
			"ON" "Habilitar método randômico?" $status_1 \
			"OFF" "Desabilitar método randômico?" $status_2 \
			--title "$m0020" --cancel-button "$m0016" --ok-button "$m0018" 3>&1 1>&2 2>&3)

        exitstatus=$?
        if [ $exitstatus = 0 ]; then
                save_DB "threadRandom" "$threadRandom" "$new_threadRandom"
                go_operation
        else
            go_operation
        fi
}

edit_threadNumber() {
        new_threadNumber=$(NEWT_COLORS="${newtcols[@]} ${newtcols_error[@]}" whiptail --inputbox "$m0004 $threadNumber" 9 78 $threadNumber \
                --title "$m0021" --cancel-button "$m0016" --ok-button "$m0018" 3>&1 1>&2 2>&3)

        exitstatus=$?
        if [ $exitstatus = 0 ]; then
                save_DB "threadNumber" "$threadNumber" "$new_threadNumber"
                go_operation
        else
            go_operation
        fi
}

edit_threadMin() {
        new_threadMin=$(NEWT_COLORS="${newtcols[@]} ${newtcols_error[@]}" whiptail --inputbox "$m0004 $threadMin" 9 78 $threadMin \
                --title "$m0022" --cancel-button "$m0016" --ok-button "$m0018" 3>&1 1>&2 2>&3)

        exitstatus=$?
        if [ $exitstatus = 0 ]; then
                save_DB "threadMin" "$threadMin" "$new_threadMin"
                go_operation
        else
            go_operation
        fi
}

edit_threadMax() {
        new_threadMax=$(NEWT_COLORS="${newtcols[@]} ${newtcols_error[@]}" whiptail --inputbox "$m0004 $threadMax" 9 78 $threadMax \
                --title "$m0023" --cancel-button "$m0016" --ok-button "$m0018" 3>&1 1>&2 2>&3)

        exitstatus=$?
        if [ $exitstatus = 0 ]; then
                save_DB "threadMax" "$threadMax" "$new_threadMax"
                go_operation
        else
            go_operation
        fi
}

edit_lowCPU() {

		status_1=""
		status_2=""
		
		if [ $threadRandom = "ON" ] 
		then
			status_1="ON"
			status_2="OFF"
		else
			status_1="OFF"
			status_2="ON"
		fi

        new_lowCPU=$(NEWT_COLORS="${newtcols[@]} ${newtcols_error[@]}" whiptail --radiolist \
			" " 8 60 2 \
			"ON" "Habilitar baixo consumo de CPU?" $status_1 \
			"OFF" "Desabilitar baixo consumo de CPU?" $status_2 \
			--title "$m0024" --cancel-button "$m0016" --ok-button "$m0018" 3>&1 1>&2 2>&3)

        exitstatus=$?
        if [ $exitstatus = 0 ]; then
                save_DB "lowCPU" "$lowCPU" "$new_lowCPU"
                go_operation
        else
            go_operation
        fi
}

edit_lowCPUFrom() {
        new_lowCPUFrom=$(NEWT_COLORS="${newtcols[@]} ${newtcols_error[@]}" whiptail --inputbox "$m0004 $lowCPUFrom - Seguir o modelo HH:MM, Exemplo:22:30" 9 78 $lowCPUFrom \
                --title "$m0025" --cancel-button "$m0016" --ok-button "$m0018" 3>&1 1>&2 2>&3)

        exitstatus=$?
        if [ $exitstatus = 0 ]; then
                save_DB "lowCPUFrom" "$lowCPUFrom" "$new_lowCPUFrom"
                go_operation
        else
            go_operation
        fi
}

edit_lowCPUTo() {
        new_lowCPUTo=$(NEWT_COLORS="${newtcols[@]} ${newtcols_error[@]}" whiptail --inputbox "$m0004 $lowCPUTo - Seguir o modelo HH:MM, Exemplo:22:30" 9 78 $lowCPUTo \
                --title "$m0026" --cancel-button "$m0016" --ok-button "$m0018" 3>&1 1>&2 2>&3)

        exitstatus=$?
        if [ $exitstatus = 0 ]; then
                save_DB "lowCPUTo" "$lowCPUTo" "$new_lowCPUTo"
                go_operation
        else
            go_operation
        fi
}
				
go_operation() {
        menu_operation=$(NEWT_COLORS="${newtcols[@]} ${newtcols_error[@]}" whiptail \
                --title "$iTitle" --cancel-button "$m0014" --ok-button "$m0015" --menu "$m0019" 16 60 7 \
                "$m0020" "     $threadNumber" \
                "$m0021" "     $threadRandom" \
                "$m0022" "     $threadMin" \
                "$m0023" "     $threadMax" \
                "$m0024" "     $lowCPU" \
                "$m0025" "     $lowCPUFrom" \
                "$m0026" "     $lowCPUTo" \
                3>&1 1>&2 2>&3)

        exitstatus=$?
        if [ $exitstatus = 0 ]; then
                case $menu_operation in
                        "$m0020") edit_threadRandom;;
                        "$m0021") edit_threadNumber;;
                        "$m0022") edit_threadMin;;
                        "$m0023") edit_threadMax;;
                        "$m0024") edit_lowCPU;;
                        "$m0025") edit_lowCPUFrom;;
                        "$m0026") edit_lowCPUTo;;
                esac
        else
                go_main
        fi
}

go_main() {
        main=$(NEWT_COLORS="${newtcols[@]} ${newtcols_error[@]}" whiptail \
                --title "$iTitle" --cancel-button "$m0017" --ok-button "$m0015" --menu "\n       Selecione abaixo a opção desejada" 11 60 2 \
                "1" "Editar o módulo de conexão com Proxy XMR?"  \
                "2" "Editar os parâmetros de operação?" \
                3>&1 1>&2 2>&3)

        exitstatus=$?
        if [ $exitstatus = 0 ]; then
                case $main in
                        1)go_proxy;;
                        2)go_operation;;
                esac
        else
                echo "You chose Cancel."
        fi
}

if (NEWT_COLORS="${newtcols[@]} ${newtcols_error[@]}" whiptail \
        --title "$iTitle" --yesno --yes-button "Sim" --no-button "Não" \
        "$m0001\n\n$m0002" 10 60)
then
        go_main
else
        clear
fi

