#!/bin/bash
#
#
load_DB() {
        . /opt/monitor/monitorDB
}

load_DB

readarray -t newtcols < /etc/newt/palette
myBackground=blue

newtcols_error=(
        window=,lightgray
        border=black,lightgray
        textbox=black,lightgray
        button=white,red

        root=,$myBackground
        checkbox=,$myBackground
        entry=,$myBackground
        label=$myBackground,
        actlistbox=,$myBackground
        helpline=,$myBackground
        roottext=green,$myBackground
        emptyscale=$myBackground
        disabledentry=$myBackground,
)


iTitle="Monitor config interface"
m0001="Utilize essa ferramenta para alterar as configurações da base de dados do Monitor"
m0002="Deseja prosseguir?"
m0003="Veja abaixo a configuração atual, para alterar, selecione o número a frente de cada parâmetro"
m0004="Valor atual:"
m0005="Defina o novo endereço IP ou URL para conexão com a Pool"
m0006="Defina o novo número da porta de conexão com a Pool"
m0007="Defina o novo protocolo de conexão com a Pool"
m0008="Defina o novo algoritmo de conexão com a Pool"
m0009="Defina o endereço da sua Wallet"
m0010="Defina um nome para o parâmetro WorkerName"
m0011="Informe o seu endereço de E-mail"
m0012="Defina um proxy para conexão com a Internet"
m0013="Deseja utilizar um metodo randomico para alocar o número de Threads?"
m0014="Defina o número de Threads para mineração"

save_DB(){
        sed -e "s%$1=$2%$1=$3%g" /opt/monitor/monitorDB \
        > /opt/monitor/monitorDB.tmp

        mv /opt/monitor/monitorDB.tmp /opt/monitor/monitorDB

        load_DB
}

edit_algorithm()
{
        new_algorithm=$(NEWT_COLORS="${newtcols[@]} ${newtcols_error[@]}" whiptail --inputbox "$m0004 $algorithm" 8 78 $algorithm \
                --title "$m0008" --cancel-button "Cancelar" --ok-button "Salvar" 3>&1 1>&2 2>&3)

        exitstatus=$?
        if [ $exitstatus = 0 ]; then
                save_DB "algorithm" "$algorithm" "$new_algorithm"
                go_proxy
        else
            go_proxy
        fi
}

edit_protocol(){
        new_protocol=$(NEWT_COLORS="${newtcols[@]} ${newtcols_error[@]}" whiptail --inputbox "$m0004 $protocol" 8 78 $protocol \
                --title "$m0007" --cancel-button "Cancelar" --ok-button "Salvar" 3>&1 1>&2 2>&3)

        exitstatus=$?
        if [ $exitstatus = 0 ]; then
                save_DB "protocol" "$protocol" "$new_protocol"
                go_proxy
        else
            go_proxy
        fi
}

edit_ipAddress(){
        new_ip=$(NEWT_COLORS="${newtcols[@]} ${newtcols_error[@]}" whiptail --inputbox "$m0004 $ip" 8 78 $ip \
                --title "$m0005" --cancel-button "Cancelar" --ok-button "Salvar" 3>&1 1>&2 2>&3)

        exitstatus=$?
        if [ $exitstatus = 0 ]; then
                save_DB "ip" "$ip" "$new_ip"
                go_proxy
        else
            go_proxy
        fi
}

edit_port () {
        new_port=$(NEWT_COLORS="${newtcols[@]} ${newtcols_error[@]}" whiptail --inputbox "$m0004 $port" 8 78 $port \
                --title "$m0006" --cancel-button "Cancelar" --ok-button "Salvar" 3>&1 1>&2 2>&3)

        exitstatus=$?
        if [ $exitstatus = 0 ]; then
                save_DB "port" "$port" "$new_port"
                go_proxy
        else
            go_proxy
        fi
}

edit_WalletAddress() {
        new_WalletAddress=$(NEWT_COLORS="${newtcols[@]} ${newtcols_error[@]}" whiptail --inputbox "$m0004 $WalletAddress" 8 78 $WalletAddress \
                --title "$m0009" --cancel-button "Cancelar" --ok-button "Salvar" 3>&1 1>&2 2>&3)

        exitstatus=$?
        if [ $exitstatus = 0 ]; then
                save_DB "WalletAddress" "$WalletAddress" "$new_WalletAddress"
                go_proxy
        else
            go_proxy
        fi
}

edit_WorkerName() {
        new_WorkerName=$(NEWT_COLORS="${newtcols[@]} ${newtcols_error[@]}" whiptail --inputbox "$m0004 $WorkerName" 8 78 $WorkerName \
                --title "$m0010" --cancel-button "Cancelar" --ok-button "Salvar" 3>&1 1>&2 2>&3)

        exitstatus=$?
        if [ $exitstatus = 0 ]; then
                save_DB "WorkerName" "$WorkerName" "$new_WorkerName"
                go_proxy
        else
            go_proxy
        fi
}

edit_Email() {
        new_Email=$(NEWT_COLORS="${newtcols[@]} ${newtcols_error[@]}" whiptail --inputbox "$m0004 $Email" 8 78 $Email \
                --title "$m0011" --cancel-button "Cancelar" --ok-button "Salvar" 3>&1 1>&2 2>&3)

        exitstatus=$?
        if [ $exitstatus = 0 ]; then
                save_DB "Email" "$Email" "$new_Email"
                go_proxy
        else
            go_proxy
        fi
}

edit_proxy() {
        new_proxy=$(NEWT_COLORS="${newtcols[@]} ${newtcols_error[@]}" whiptail --inputbox "$m0004 $proxy" 8 78 $proxy \
                --title "$m0012" --cancel-button "Cancelar" --ok-button "Salvar" 3>&1 1>&2 2>&3)

        exitstatus=$?
        if [ $exitstatus = 0 ]; then
                save_DB "proxy" "$proxy" "$new_proxy"
                go_proxy
        else
            go_proxy
        fi
}

go_proxy() {
        menu_proxy=$(NEWT_COLORS="${newtcols[@]} ${newtcols_error[@]}" whiptail \
                --title "$iTitle" --cancel-button "Voltar" --ok-button "Selecionar" --menu "Selecione o parâmetro que deseja alterar" 22 68 16 \
                "Pool-Algoritmo" "     $algorithm" \
                "Pool-Protocolo" "     $protocol" \
                "Pool-Endereço-IP" "     $ip" \
                "Pool-Porta" "     $port" \
                "Pool-Wallet-Address" "     "$(echo $WalletAddress | awk '{print substr ($0, 0, 15)}' )"..." \
                "Pool-Worker-Name" "     $WorkerName" \
                "Pool-Email" "     $Email" \
                "Internet-Proxy" "     $proxy" \
                3>&1 1>&2 2>&3)

        exitstatus=$?
        if [ $exitstatus = 0 ]; then
                case $menu_proxy in
                        Pool-Algoritmo) edit_algorithm;;
                        Pool-Protocolo) edit_protocol;;
                        Pool-Endereço-IP) edit_ipAddress;;
                        Pool-Porta) edit_port;;
                        Pool-Wallet-Address) edit_WalletAddress;;
                        Pool-Worker-Name) edit_WorkerName;;
                        Pool-Email) edit_Email;;
                        Internet-Proxy) edit_proxy;;
                esac
        else
                go_main
        fi
}
##################################################################################################################

edit_threadNumber() {
        new_threadNumber=$(NEWT_COLORS="${newtcols[@]} ${newtcols_error[@]}" whiptail --inputbox "$m0004 $threadNumber" 8 78 $threadNumber \
                --title "$m0014" --cancel-button "Cancelar" --ok-button "Salvar" 3>&1 1>&2 2>&3)

        exitstatus=$?
        if [ $exitstatus = 0 ]; then
                save_DB "threadNumber" "$threadNumber" "$new_threadNumber"
                go_operation
        else
            go_operation
        fi
}

edit_threadRandom() {

		status_1=""
		status_2=""
		
		if [ $threadRandom = "ON" ] 
		then
			status_1="ON"
			status_2="OFF"
		else
			status_1="OFF"
			status_2="ON"
		fi

        new_threadRandom=$(NEWT_COLORS="${newtcols[@]} ${newtcols_error[@]}" whiptail --radiolist \
			" " 15 50 5 \
			"ON" "Habilitar método randômico?" $status_1 \
			"OFF" "Desabilitar método randômico?" $status_2 \
			--title "$m0013" --cancel-button "Cancelar" --ok-button "Salvar" 3>&1 1>&2 2>&3)

        exitstatus=$?
        if [ $exitstatus = 0 ]; then
                save_DB "threadRandom" "$threadRandom" "$new_threadRandom"
                go_operation
        else
            go_operation
        fi
}


go_operation() {
        menu_operation=$(NEWT_COLORS="${newtcols[@]} ${newtcols_error[@]}" whiptail \
                --title "$iTitle" --cancel-button "Voltar" --ok-button "Selecionar" --menu "Selecione o parâmetro que deseja alterar" 22 68 16 \
                "Metodo-Randomico" "     $threadRandom" \
                "CPU-Threads" "     $threadNumber" \
                "CPU-Threads-Minimo" "     $threadMin" \
                "CPU-Threads-Máximo" "     $threadMax" \
                "CPU-Baixo-Consumo" "     $lowCPU" \
                "Baixo-Consumo-Inicio" "     $lowCPUFrom" \
                "Baixo-Consumo-Fim" "     $lowCPUTo" \
                3>&1 1>&2 2>&3)

        exitstatus=$?
        if [ $exitstatus = 0 ]; then
                case $menu_operation in
                        Metodo-Randomico) edit_threadRandom;;
                        CPU-Threads) edit_threadNumber;;
                        CPU-Threads-Minimo) edit_threadMin;;
                        CPU-Threads-Máximo) edit_threadMax;;
                        CPU-Baixo-Consumo) edit_lowCPU;;
                        Baixo-Consumo-Inicio) edit_lowCPUFrom;;
                        Baixo-Consumo-Fim) edit_lowCPUTo;;
                esac
        else
                go_main
        fi
}

go_main() {
        main=$(NEWT_COLORS="${newtcols[@]} ${newtcols_error[@]}" whiptail \
                --title "$iTitle" --cancel-button "Sair" --ok-button "Selecionar" --menu "Selecione a opção desejada" 15 60 4 \
                "1" "Editar o módulo de conexão com Proxy XMR?"  \
                "2" "Editar os parametros de operação?" \
                3>&1 1>&2 2>&3)

        exitstatus=$?
        if [ $exitstatus = 0 ]; then
                case $main in
                        1)go_proxy;;
                        2)go_operation;;
                esac
        else
                echo "You chose Cancel."
        fi
}

if (NEWT_COLORS="${newtcols[@]} ${newtcols_error[@]}" whiptail \
        --title "$iTitle" --yesno --yes-button "Sim" --no-button "Não" \
        "$m0001\n\n$m0002" 10 60)
then
        go_main
else
        clear
fi

